version: '2'
networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
services:
  server:
    build: ./server
    networks:
      app:
        ipv4_address: 172.21.1.1
    ports:
      - "3306:3306"
    tty: true
    privileged: true
    command: /sbin/init
